[General]
# Enable Debug message output
EnableDebugLogging = true

[Config]
# File that BetaComment writes to
BetaCommentFileName = "BetaComment.txt"

[Patches]
# Load EditorIDs for most Forms to use them in the console or in logging
EnableLoadingEditorIDs = true

# Log any EditorID conflicts found while EnabledLoadingEditorIDs is true
EnableEditorIDConflictCheck = false

[Features]
# Enable Fallout 76 Style Power Armor Frame Storage
EnablePowerArmorStorage = true
