name: Build

on:
  push:
    branches: [main]
    paths-ignore: ["**/*.md"]
  pull_request:
    paths-ignore: ["**/*.md"]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_build.yml
